// Nine themes for skeleton A. Each is its own setting, cast, motive and set of red herrings; the puzzle
// structure and every answer are generated and machine-verified by skeleton-a.mjs / engine.mjs.
// People order is fixed: [victim, culprit, inspector, outsider, herring1, herring2, herring3, bystander x7].
// Departments of culprit, inspector, herring1 and outsider must all differ.

const P = (name, role, dept) => ({ name, role, dept });

export const THEMES = [
  {
    motive: "Alistair had discovered that Camille forged the provenance papers for the museum's newest acquisition, and he was about to expose her to the board.", slug: 'midnight_gala', title: 'The Midnight Gala', date: '2025-05-09', seed: 1101,
    hook: "The Harbor Museum's anniversary gala was meant to end with the director's toast. Instead Alistair Wren collapsed at the podium and never got up. The toasting decanter had been laced. Everyone was in the building, and the museum logs everything.",
    timeline: { intervalStart: '21:00' }, area: 'COLLECTIONS_VAULT', wing: 'DIRECTOR_SUITE',
    doors: ['STAFF_ENTRANCE', 'LOBBY', 'GALLERY_EAST', 'GALLERY_WEST'],
    tables: { roster: 'staff_roster', access: 'door_log', custody: 'vault_custody', messages: 'messages' },
    item: 'Toasting Decanter', otherItems: ['Welcome Plaque', 'Ribbon Scissors', 'Speech Cards'], custodyLabel: 'vault custody log',
    itemWords: { checkedIn: 'Received from catering, sealed', filled: 'Poured for the toast, bottle lot', returned: 'Back on the vault shelf', inspected: 'Seal intact, liquid clear', refilled: 'Topped up from bottle lot', taken: 'Carried to the podium', used: 'Raised for the director toast' },
    messages: {
      threat1: 'I have seen the provenance papers, Camille. They do not match. Explain yourself to the board or I will.',
      plea: 'Please. There is an explanation. Give me until after the gala.',
      threat2: 'This is your last chance. After the toast I am calling the board chair.',
      errand: 'During the speeches interval, could you bring my reading glasses from the vault shelf?',
      herring1Wish: 'Good luck with the toast tonight. Your new wing is beautiful.',
      herring2Row: 'We need to talk about your spending. The board is not happy.',
      herring3Money: 'The Hargrove pledge is still unpaid and you promised it tonight.',
      culpritReady: 'The decanter is ready for you, Alistair. It will be a night to remember.',
      chatter: ['Bring more canapes to the east gallery', 'Mic check at nine, please', 'Embargo lifts at ten', 'Spotlight on the stairs at nine thirty'],
      aftermath: 'Terrible news. I am staying for the police.',
    },
    clues: [
      'The decanter sat in the locked collections vault during the speeches interval. The staff roster and the door badge logs are now open to you. Who could have reached it?',
      'Only a handful of people got into the vault during the interval. The vault custody log shows who touched the decanter and what went into it.',
      "The director's phone was recovered. His messages show who was angry with him and who he feared. Put the logs, the custody record and the messages together and name the one person who fits every piece.",
    ],
    people: [
      P('Alistair Wren', 'Museum Director', 'Management'), P('Camille Dorsey', 'Registrar', 'Collections'), P('Silas Park', 'Head of Security', 'Security'),
      P('Tobias Reed', 'Catering Runner', 'Catering'), P('Imogen Hale', 'Visiting Artist', 'Exhibitors'), P('Marguerite Voss', 'Board Chair', 'Board'),
      P('Dennis Okafor', 'Donor Liaison', 'Development'), P('Priya Menon', 'Curator of Asia', 'Curatorial'), P('Hugo Lindqvist', 'Lighting Technician', 'Technical'),
      P('Sofia Alvarez', 'Conservator', 'Conservation'), P('Walter Finch', 'Coat Check', 'Front of House'), P('Nadia Rahman', 'Press Officer', 'Communications'),
      P('Felix Brandt', 'Sound Engineer', 'Technical'), P('Eleanor Quill', 'Art Critic', 'Guest'),
    ],
  },
  {
    motive: "Lord Pemberton had found out that Raoul was smuggling contraband crates through the cellar and planned to report him at the next port.", slug: 'last_voyage_aurora', title: 'The Last Voyage of the Aurora', date: '2025-06-21', seed: 2202,
    hook: "On the final night of the Aurora's Atlantic crossing, Lord Pemberton raised his glass at the captain's table and fell silent for good. The vintage in his glass had been tampered with. The ship's logs record every door, every bottle and every message.",
    timeline: { intervalStart: '20:30' }, area: 'WINE_CELLAR', wing: 'CAPTAIN_DECK',
    doors: ['CREW_GANGWAY', 'MAIN_LOUNGE', 'GALLEY', 'PROMENADE'],
    tables: { roster: 'ship_roster', access: 'deck_access', custody: 'cellar_book', messages: 'cabin_texts' },
    item: 'Vintage Magnum', otherItems: ['Cheese Board', 'Ice Bucket', 'Menu Cards'], custodyLabel: 'cellar book',
    itemWords: { checkedIn: 'Logged into the cellar, wax seal intact', filled: 'Decanted for dinner, batch', returned: 'Returned to the cellar rack', inspected: 'Cork and seal checked', refilled: 'Decanted again from batch', taken: 'Sent up to the captain table', used: 'Poured for the toast' },
    messages: {
      threat1: 'I know about the crates you have been loading at night, Raoul. I will report it to customs at the next port.',
      plea: 'It is not what you think. Let me explain before we dock.',
      threat2: 'Last chance. Tonight after dinner I am telling the captain.',
      errand: 'During the interval could you fetch the captain\'s spare cuff links from the cellar shelf?',
      herring1Wish: 'Have a wonderful dinner, my lord. The crossing has been a dream.',
      herring2Row: 'You cannot cut my allowance. We are not finished discussing it.',
      herring3Money: 'The investment you promised me. I expect it before we land.',
      culpritReady: 'Your special bottle is ready, my lord. A night to remember.',
      chatter: ['Extra towels needed on deck four', 'Band starts at nine', 'Galley is out of lemons', 'Weather looks calm tonight'],
      aftermath: 'Dreadful business. We will not reach port before the investigators come aboard.',
    },
    clues: [
      'The magnum waited in the locked wine cellar during the interval before the toast. The ship roster and the deck access logs are open to you. Who could reach it?',
      'Only a few people entered the cellar during that interval. The cellar book shows who handled the magnum and what went into it.',
      "Lord Pemberton's cabin phone was recovered. Together with the logs and the cellar book, his messages point to one person who fits every piece. Name them.",
    ],
    people: [
      P('Lord Edmund Pemberton', 'First-Class Passenger', 'Passengers'), P('Raoul Vance', 'Sommelier', 'Wine Service'), P('Captain Ingrid Solheim', 'Captain', 'Bridge'),
      P('Pip Tanaka', 'Deck Steward', 'Stewards'), P('Beatrice Lang', 'Pianist', 'Entertainment'), P('Lady Cordelia Pemberton', 'Passenger', 'Family'),
      P('Rupert Ashgrove', 'Investor', 'Guests'), P('Anselm Brooke', 'Purser', 'Administration'), P('Yusuf Karim', 'Head Chef', 'Galley'),
      P('Greta Lindholm', 'Ship Doctor', 'Medical'), P('Joaquin Reyes', 'Bartender', 'Bar Service'), P('Marcy Dunn', 'Cruise Director', 'Activities'),
      P('Olga Petrova', 'Radio Officer', 'Communications'), P('Hamish Reid', 'Travel Writer', 'Press'),
    ],
  },
  {
    motive: "Winifred had discovered that Dorothea passed off a famous recipe as her own and threatened to tell the producers after the judging.", slug: 'bakeoff_betrayal', title: 'The Great Bake-Off Betrayal', date: '2025-07-12', seed: 3303,
    hook: 'Judge Winifred Marsh took one bite of the winning cake and collapsed in front of the cameras. The tent logs, the pantry book and everyone\'s phones will show who spoiled the cake.',
    timeline: { intervalStart: '20:00' }, area: 'PANTRY_TENT', wing: 'JUDGES_TENT',
    doors: ['CREW_GATE', 'MAIN_MARQUEE', 'OVEN_ROW', 'CAR_PARK'],
    tables: { roster: 'tent_roster', access: 'tent_scans', custody: 'pantry_book', messages: 'phone_texts' },
    item: 'Showstopper Cake', otherItems: ['Sugar Flowers', 'Cake Stand', 'Tasting Spoons'], custodyLabel: 'pantry book',
    itemWords: { checkedIn: 'Delivered by the contestant, boxed', filled: 'Final layer assembled, icing batch', returned: 'Returned to the pantry chiller', inspected: 'Looks and smells fine, judges tasting table next', refilled: 'Extra glaze added from icing batch', taken: 'Wheeled to the judging table', used: 'First slice cut by the head judge' },
    messages: {
      threat1: 'I tasted your recipe notes, Dorothea. They are Mary Tuttle\'s recipe, word for word. Confess or I tell the producers.',
      plea: 'Winifred, please. It was an accident. Give me the evening.',
      threat2: 'Final warning. Right after the judging I am calling the producers.',
      errand: 'At the interval please grab my clipboard from the pantry shelf.',
      herring1Wish: 'Good luck judging tonight. The cake looks glorious.',
      herring2Row: 'You marked my sponge down on purpose. I will not forget this.',
      herring3Money: 'The sponsorship cheque you promised the show. Where is it?',
      culpritReady: 'Your cake is ready for the table, Winifred. It is going to be a night to remember.',
      chatter: ['More butter to oven row please', 'Camera two needs a battery', 'Raffle tickets are sold out', 'Rain is coming at ten'],
      aftermath: 'Awful news. I will wait for the police at the marquee.',
    },
    clues: [
      'The showstopper cake sat in the pantry tent during the interval. The tent roster and the gate scans are open to you. Who could reach it?',
      'Only a few people entered the pantry during the interval. The pantry book shows who handled the cake and what was added.',
      "Winifred's phone was recovered. Her messages, the logs and the pantry book point to one person who fits every piece. Name them.",
    ],
    people: [
      P('Winifred Marsh', 'Head Judge', 'Judges'), P('Dorothea Finch', 'Contestant', 'Bakers'), P('Percival Stone', 'Tent Manager', 'Operations'),
      P('Kit Baxter', 'Runner', 'Runners'), P('Mabel Okoye', 'Host', 'Presenters'), P('Gordon Tuttle', 'Co-Judge', 'Panel'),
      P('Selena Voss', 'Sponsor Rep', 'Sponsors'), P('Arjun Mehta', 'Contestant', 'Bakers'), P('Lottie Brandt', 'Camera Operator', 'Crew'),
      P('Hector Dunn', 'Sound Technician', 'Crew'), P('Ruth Ashby', 'Producer', 'Production'), P('Cleo Hartman', 'Food Stylist', 'Styling'),
      P('Bram Visser', 'Contestant', 'Bakers'), P('Edith Crane', 'Village Fair Organiser', 'Guests'),
    ],
  },
  {
    motive: "Helena had found that Matthias falsified research readings and planned to inform the board after the viewing night.", slug: 'observatory_incident', title: 'The Observatory Incident', date: '2025-09-02', seed: 4404,
    hook: "During the Perseids viewing night, Dr. Helena Voss, the observatory's director, collapsed at the main telescope after a sip of her cocoa. The observatory's access log, supply book and radio texts will show who tampered with the thermos.",
    timeline: { intervalStart: '22:00' }, area: 'COLD_STORE', wing: 'DIRECTOR_OFFICE',
    doors: ['SERVICE_GATE', 'DOME_FOYER', 'WORKSHOP', 'ROOFTOP_STAIR'],
    tables: { roster: 'observatory_staff', access: 'keycard_swipes', custody: 'supply_book', messages: 'radio_texts' },
    item: 'Cocoa Thermos', otherItems: ['Star Charts', 'Red Torch', 'Lens Cloth'], custodyLabel: 'supply book',
    itemWords: { checkedIn: 'Signed in from the kitchen, sealed lid', filled: 'Filled for the director, mix batch', returned: 'Back in the cold store', inspected: 'Lid sealed, contents look normal', refilled: 'Topped up from mix batch', taken: 'Brought to the main dome', used: 'Opened by the director' },
    messages: {
      threat1: 'I found the falsified readings, Matthias. Report them to the board yourself or I will.',
      plea: 'Helena, please, let me explain the data first.',
      threat2: 'This is final. After tonight\'s viewing I am emailing the board.',
      errand: 'In the break could you bring my notebook from the cold store shelf?',
      herring1Wish: 'Clear skies for tonight, Dr. Voss. The forecast is perfect.',
      herring2Row: 'You cut my telescope time again. I am not done with this.',
      herring3Money: 'The grant money you promised for my project. I need an answer.',
      culpritReady: 'Your cocoa is ready, Helena. Tonight will be unforgettable.',
      chatter: ['Dome shutter is sticking again', 'Coffee machine is empty', 'Seeing is excellent tonight', 'Guests arrive at half past ten'],
      aftermath: 'Heartbreaking. I will stay until the police arrive.',
    },
    clues: [
      'The thermos sat in the locked cold store during the break in the viewing programme. The staff roster and the keycard swipes are open to you. Who could reach it?',
      'Only a few keycards opened the cold store during the break. The supply book shows who handled the thermos and what went into it.',
      "Helena's radio phone was recovered. With the swipes and the supply book, her texts point to one person who fits every piece. Name them.",
    ],
    people: [
      P('Dr. Helena Voss', 'Observatory Director', 'Directorate'), P('Matthias Kroll', 'Data Analyst', 'Research Data'), P('Ingrid Lang', 'Head of Facilities', 'Facilities'),
      P('Nico Alvarez', 'Night Assistant', 'Operations'), P('Zara Nwosu', 'PhD Student', 'Students'), P('Prof. Leopold Marsh', 'Senior Astronomer', 'Faculty'),
      P('Celeste Brandt', 'Grants Officer', 'Administration'), P('Owen Park', 'Telescope Operator', 'Operations'), P('Mina Sato', 'Outreach Lead', 'Outreach'),
      P('Tomas Reyes', 'Electrician', 'Facilities'), P('Beatrix Hale', 'Librarian', 'Library'), P('Idris Ahmed', 'IT Technician', 'IT'),
      P('Sven Holm', 'Astrophotographer', 'Guests'), P('Doris Whitlock', 'Journalist', 'Press'),
    ],
  },
  {
    motive: "Sir Gideon had found irregularities in Lucian's ledgers about the diamonds and threatened to call the police at the next stop.", slug: 'orient_night_express', title: 'Murder on the Night Express', date: '2025-10-31', seed: 5505,
    hook: "The overnight express was crossing the mountains when diamond merchant Sir Gideon Bauer raised his after-dinner tea and fell dead in the dining car. The train's door sensors, pantry log and passenger phones know who spiked the tea service.",
    timeline: { intervalStart: '21:15' }, area: 'PANTRY_CAR', wing: 'FIRST_CLASS_CORRIDOR',
    doors: ['STATION_STEP', 'DINING_CAR', 'SLEEPER_ONE', 'OBSERVATION_CAR'],
    tables: { roster: 'train_manifest', access: 'door_sensors', custody: 'pantry_ledger', messages: 'passenger_texts' },
    item: 'Silver Tea Service', otherItems: ['Biscuit Tin', 'Napkin Set', 'Sugar Tongs'], custodyLabel: 'pantry ledger',
    itemWords: { checkedIn: 'Loaded at the station, sealed tin', filled: 'Brewed for dinner service, tea batch', returned: 'Returned to the pantry shelf', inspected: 'Seal and pot checked', refilled: 'Fresh pot made from tea batch', taken: 'Rolled into the dining car', used: 'Poured at the merchant table' },
    messages: {
      threat1: 'I have seen your ledgers, Lucian. The diamonds do not add up. Explain or I go to the police at the next stop.',
      plea: 'Sir Gideon, please. We can fix this quietly.',
      threat2: 'Final chance. When the train stops at the summit I am calling the inspector.',
      errand: 'During the interval please bring the lost-property list from the pantry shelf.',
      herring1Wish: 'Enjoy your tea this evening, Sir Gideon. The mountains are lovely.',
      herring2Row: 'You promised me a share of the deal. I am still waiting.',
      herring3Money: 'The loan you called in. I cannot pay it back this week.',
      culpritReady: 'Your tea is ready, Sir Gideon. It will be a night to remember.',
      chatter: ['Extra blankets for car three', 'Dessert trolley is running late', 'Signal at the next tunnel', 'Lamp is out in the corridor'],
      aftermath: 'Shocking. The train will wait for the police at the summit.',
    },
    clues: [
      'The tea service sat in the locked pantry car during the interval before the after-dinner round. The train manifest and the door sensor logs are open to you. Who could reach it?',
      'Only a handful of people entered the pantry car during the interval. The pantry ledger shows who handled the tea service and what went into it.',
      "Sir Gideon's phone was recovered. Combine his messages with the sensors and the ledger to name the one person who fits every piece.",
    ],
    people: [
      P('Sir Gideon Bauer', 'Diamond Merchant', 'First Class'), P('Lucian Moreau', 'Dining Car Steward', 'Catering'), P('Inspector Hana Ito', 'Train Security', 'Security'),
      P('Pietro Vale', 'Porter', 'Porters'), P('Seraphine Duval', 'Opera Singer', 'Entertainers'), P('Madame Oriel Fontaine', 'Widow', 'Passengers'),
      P('Casper Lindgren', 'Business Partner', 'Business'), P('Ada Weller', 'Conductor', 'Operations'), P('Bruno Castell', 'Cook', 'Catering'),
      P('Fatima Haddad', 'Doctor', 'Passengers'), P('Jules Bernard', 'Valet', 'Staff'), P('Rosalind Keene', 'Novelist', 'Passengers'),
      P('Tobias Wren', 'Engineer', 'Locomotive Crew'), P('Agnes Pruitt', 'Newspaper Reporter', 'Press'),
    ],
  },
  {
    motive: "Professor Crane had discovered that Verity copied published results into her lab notebook and planned to report her to the committee.", slug: 'fatal_finals', title: 'Fatal Finals', date: '2025-12-10', seed: 6606,
    hook: 'On the night of the chemistry finals, Professor Aldous Crane drank from his coffee flask during the invigilation break and never finished the exam. The lab swipe log, the stores register and the department chat will show who altered the flask.',
    timeline: { intervalStart: '20:45' }, area: 'CHEM_STORE', wing: 'PROFESSOR_OFFICES',
    doors: ['STAFF_DOOR', 'EXAM_HALL', 'LAB_THREE', 'LIBRARY_LINK'],
    tables: { roster: 'faculty_roster', access: 'swipe_log', custody: 'stores_register', messages: 'dept_chat' },
    item: 'Coffee Flask', otherItems: ['Exam Papers', 'Stopwatch', 'Spare Pens'], custodyLabel: 'stores register',
    itemWords: { checkedIn: 'Signed in at the store for the professor, sealed lid', filled: 'Filled in the staff room, batch', returned: 'Back on the stores shelf', inspected: 'Lid sealed, checked by the invigilator', refilled: 'Topped up from batch', taken: 'Carried to the invigilator desk', used: 'Opened by the professor' },
    messages: {
      threat1: 'I have compared your lab notebook with the published data, Verity. The results were copied. Tell the committee yourself or I will.',
      plea: 'Professor, please, give me until after the finals.',
      threat2: 'Last chance. After the exam I am reporting you to the committee.',
      errand: 'During the break could you bring my exam binder from the store shelf?',
      herring1Wish: 'Good luck invigilating tonight, Professor. The paper looks fair.',
      herring2Row: 'You failed my entire group. This is not over.',
      herring3Money: 'The department funds you promised me. I need an answer.',
      culpritReady: 'Your coffee is ready, Professor. It will be a night to remember.',
      chatter: ['Extra desks for hall B', 'Printer is jammed again', 'Exam clock is five minutes slow', 'Fire alarm test at ten'],
      aftermath: 'Terrible. I will stay until security arrives.',
    },
    clues: [
      'The flask sat in the locked chemical store during the break in the finals. The faculty roster and the swipe log are open to you. Who could reach it?',
      'Only a few cards opened the store during the break. The stores register shows who handled the flask and what went into it.',
      "The professor's department chat was recovered. With the swipes and the register, it points to one person who fits every piece. Name them.",
    ],
    people: [
      P('Prof. Aldous Crane', 'Head of Chemistry', 'Faculty'), P('Verity Holt', 'Lab Technician', 'Laboratory'), P('Magnus Ekberg', 'Exam Invigilator', 'Examinations'),
      P('Dev Patel', 'Porter', 'Porters'), P('Hannah Keller', 'Graduate Teaching Assistant', 'Graduate School'), P('Dr. Silvia Marconi', 'Lecturer', 'Lecturers'),
      P('Gareth Pryce', 'Research Fellow', 'Research'), P('Leona Frost', 'Exam Officer', 'Registry'), P('Anton Volkov', 'IT Support', 'IT'),
      P('Mei Lin', 'Librarian', 'Library'), P('Oscar Dunn', 'Security Guard', 'Estates'), P('Priscilla Aird', 'Dean\'s Assistant', 'Dean Office'),
      P('Rafael Ortiz', 'Visiting Examiner', 'Guests'), P('Beth Calloway', 'Student Newspaper Editor', 'Press'),
    ],
  },
  {
    motive: "Vincent had surveillance stills of Rosalind skimming at the cage and was going to take them to the gaming commission.", slug: 'high_roller_hotel', title: 'Last Hand at the Golden Crown', date: '2026-01-17', seed: 7707,
    hook: 'High roller Vincent Duarte lifted his signature cocktail at the final table and slumped over the cards. The casino cameras and logs never sleep: the stockroom swipes, the bar ledger and the staff chat will show who doctored the drink.',
    timeline: { intervalStart: '22:15' }, area: 'BAR_STOCKROOM', wing: 'VIP_SUITES',
    doors: ['STAFF_ENTRANCE', 'CASINO_FLOOR', 'CASHIER_CAGE', 'KITCHEN_PASS'],
    tables: { roster: 'casino_staff', access: 'badge_swipes', custody: 'bar_ledger', messages: 'staff_chat' },
    item: 'Signature Cocktail Shaker', otherItems: ['Ice Tongs', 'Cocktail Napkins', 'Garnish Tray'], custodyLabel: 'bar ledger',
    itemWords: { checkedIn: 'Issued to the bar, sealed spirits', filled: 'Mixed for the VIP table, bottle batch', returned: 'Back in the stockroom', inspected: 'Seals checked by the pit boss', refilled: 'Fresh mix from bottle batch', taken: 'Brought to the final table', used: 'Poured for the high roller' },
    messages: {
      threat1: 'I have the surveillance stills of you at the cage, Rosalind. I will take them to the gaming commission.',
      plea: 'Vincent, you do not understand. Let me explain tonight.',
      threat2: 'This is your last chance. After the final hand I am calling the commission.',
      errand: 'On the break please bring my reading glasses from the stockroom shelf.',
      herring1Wish: 'Best of luck at the final table, Mr. Duarte.',
      herring2Row: 'You owe me for the last three nights. I want it settled.',
      herring3Money: 'The marker you signed is overdue. Management wants it cleared.',
      culpritReady: 'Your drink is ready, Mr. Duarte. It will be a night to remember.',
      chatter: ['Table six needs a new dealer', 'Chips running low at the cage', 'Vegas lights at eleven', 'Parking valet is backed up'],
      aftermath: 'This is awful. I will stay and wait for the police.',
    },
    clues: [
      'The shaker sat in the locked bar stockroom during the break between hands. The staff roster and the badge swipes are open to you. Who could reach it?',
      'Only a few badges opened the stockroom during the break. The bar ledger shows who handled the shaker and what went into it.',
      "Vincent's phone was recovered. With the swipes and the ledger, his messages point to one person who fits every piece. Name them.",
    ],
    people: [
      P('Vincent Duarte', 'High Roller', 'Guests'), P('Rosalind Crow', 'Cage Supervisor', 'Cashier Cage'), P('Dante Marsh', 'Pit Boss', 'Gaming Floor'),
      P('Eli Nakamura', 'Barback', 'Food and Beverage'), P('Colette Winters', 'Cocktail Waitress', 'Hospitality'), P('Sasha Volkov', 'Dealer', 'Dealers'),
      P('Barnaby Frost', 'Pit Manager', 'Management'), P('Imani Brooks', 'Head Bartender', 'Bar'), P('Leo Castellano', 'Security Officer', 'Security'),
      P('Greta Lindqvist', 'Surveillance Operator', 'Surveillance'), P('Hector Mbeki', 'Valet', 'Guest Services'), P('Tess Hartley', 'Event Manager', 'Events'),
      P('Omar Rahman', 'Chef de Partie', 'Kitchen'), P('Nina Alvarado', 'Gambling Blogger', 'Press'),
    ],
  },
  {
    motive: "Dr. Ortega had reviewed dispensing records showing Imogen's numbers were falsified and would have reported her to the board.", slug: 'code_blue_st_brendans', title: "Code Blue at St. Brendan's", date: '2026-02-14', seed: 8808,
    hook: "During the hospital's winter gala, head surgeon Dr. Rafael Ortega took a sip from his water bottle on the ward round and collapsed. The pharmacy swipes, the ward supply log and the staff messaging app will show who tampered with the bottle.",
    timeline: { intervalStart: '20:15' }, area: 'PHARMACY', wing: 'SURGEONS_LOUNGE',
    doors: ['STAFF_ENTRANCE', 'WARD_ELEVEN', 'THEATRE_CORRIDOR', 'CAFETERIA'],
    tables: { roster: 'hospital_staff', access: 'badge_log', custody: 'ward_supply_log', messages: 'staff_messages' },
    item: 'Surgeon Water Bottle', otherItems: ['Clipboard', 'Hand Gel Bottle', 'Rounds Checklist'], custodyLabel: 'ward supply log',
    itemWords: { checkedIn: 'Signed in at the pharmacy counter, sealed cap', filled: 'Filled at the ward fountain, batch', returned: 'Returned to the pharmacy shelf', inspected: 'Cap sealed, checked by the charge nurse', refilled: 'Topped up from batch', taken: 'Brought to the ward round', used: 'Drunk by the surgeon' },
    messages: {
      threat1: 'I have reviewed the dispensing records, Imogen. The numbers are wrong. Come forward yourself or I report it to the board.',
      plea: 'Doctor, please. Let me show you the paperwork first.',
      threat2: 'Final warning. After the gala I will take it to the board chair.',
      errand: 'At the break please bring my pager charger from the pharmacy shelf.',
      herring1Wish: 'Good luck on the rounds tonight, Dr. Ortega.',
      herring2Row: 'You took my surgery slot again. This is not finished.',
      herring3Money: 'The bonus you promised the department. I need an answer today.',
      culpritReady: 'Your bottle is ready, Doctor. It will be a night to remember.',
      chatter: ['Bed twelve needs fresh linen', 'Lift three is out of service', 'Vending machine is empty', 'Visitors arrive at nine'],
      aftermath: 'Terrible news. I will wait for the police on the ward.',
    },
    clues: [
      'The surgeon\'s water bottle sat in the locked pharmacy during the evening break. The hospital roster and the badge log are open to you. Who could reach it?',
      'Only a few badges opened the pharmacy during the break. The ward supply log shows who handled the bottle and what went into it.',
      "The surgeon's messaging app was recovered. With the badge log and the supply log, it points to one person who fits every piece. Name them.",
    ],
    people: [
      P('Dr. Rafael Ortega', 'Head Surgeon', 'Surgery'), P('Imogen Pryce', 'Chief Pharmacist', 'Pharmacy'), P('Nurse Beatrice Lund', 'Charge Nurse', 'Nursing'),
      P('Felix Oduya', 'Hospital Porter', 'Porters'), P('Dr. Anika Rao', 'Anaesthetist', 'Anaesthetics'), P('Dr. Walter Hsu', 'Consultant', 'Medicine'),
      P('Gerald Frost', 'Hospital Administrator', 'Administration'), P('Poppy Hartley', 'Staff Nurse', 'Nursing'), P('Kwame Mensah', 'Radiographer', 'Radiology'),
      P('Lena Voss', 'Physiotherapist', 'Therapies'), P('Hugo Blackwell', 'Security Guard', 'Security'), P('Dina Saleh', 'Cafeteria Manager', 'Catering'),
      P('Tobias Quill', 'Charity Gala Guest', 'Guests'), P('Marisol Vega', 'Health Reporter', 'Press'),
    ],
  },
  {
    motive: "Baptiste had audited the estate accounts and found that Mathilde diverted export sales money; he would have told the family lawyer.", slug: 'chateau_lune_vintage', title: 'The Vintage of Chateau Lune', date: '2026-03-28', seed: 9909,
    hook: "At the harvest dinner of Chateau Lune, owner Baptiste Laurent raised his decanter to toast the vintage and collapsed before the first sip had settled. The cellar swipes, the barrel book and the family chat group will show who spoiled the wine.",
    timeline: { intervalStart: '20:30' }, area: 'BARREL_CELLAR', wing: 'OWNER_STUDY',
    doors: ['VINEYARD_GATE', 'TASTING_ROOM', 'PRESS_HOUSE', 'COURTYARD'],
    tables: { roster: 'estate_staff', access: 'cellar_swipes', custody: 'barrel_book', messages: 'family_chat' },
    item: 'Reserve Decanter', otherItems: ['Tasting Spittoon', 'Cork Basket', 'Menu Easel'], custodyLabel: 'barrel book',
    itemWords: { checkedIn: 'Drawn from the reserve barrel, sealed stopper', filled: 'Decanted for the dinner, barrel batch', returned: 'Back on the cellar rack', inspected: 'Stopper sealed, checked by the cellar master', refilled: 'Topped up from barrel batch', taken: 'Carried to the head table', used: 'Raised for the vintage toast' },
    messages: {
      threat1: 'I have audited the estate accounts, Mathilde. Money is missing from the export sales. Tell the family yourself or I will.',
      plea: 'Baptiste, please. I can account for every euro. Give me time.',
      threat2: 'Last warning. After the harvest dinner I speak to the family lawyer.',
      errand: 'During the break could you bring my reading glasses from the cellar shelf?',
      herring1Wish: 'Santé for tonight, Monsieur Laurent. The vintage will be superb.',
      herring2Row: 'You are cutting me out of the will. We are not finished.',
      herring3Money: 'The loan for the new press. I need your answer tonight.',
      culpritReady: 'Your decanter is ready, Baptiste. It will be a night to remember.',
      chatter: ['Candles needed in the courtyard', 'Musicians arrive at nine', 'Press house floor is wet', 'Taxi for the guests at midnight'],
      aftermath: 'Unthinkable. We must wait for the gendarmes.',
    },
    clues: [
      'The decanter sat in the locked barrel cellar during the break before the vintage toast. The estate roster and the cellar swipes are open to you. Who could reach it?',
      'Only a few swipes opened the barrel cellar during the break. The barrel book shows who handled the decanter and what went into it.',
      "Baptiste's family chat was recovered. With the swipes and the barrel book, it points to one person who fits every piece. Name them.",
    ],
    people: [
      P('Baptiste Laurent', 'Estate Owner', 'Family'), P('Mathilde Girard', 'Estate Manager', 'Management'), P('Armand Roux', 'Cellar Master', 'Cellar'),
      P('Theo Marchand', 'Waiter', 'Hospitality'), P('Odette Laurent', 'Niece', 'Relatives'), P('Gaston Laurent', 'Younger Brother', 'Heirs'),
      P('Colin Hartwell', 'Wine Merchant', 'Trade'), P('Sylvie Fontaine', 'Head Cook', 'Kitchen'), P('Jerome Blanc', 'Vineyard Foreman', 'Vineyard'),
      P('Elodie Martin', 'Sommelier', 'Tasting Room'), P('Pascal Nguyen', 'Press Operator', 'Production'), P('Camille Voss', 'Event Planner', 'Events'),
      P('Rupert Alder', 'Wine Critic', 'Guests'), P('Ines Duarte', 'Local Journalist', 'Press'),
    ],
  },
];
